site_name: textle documentation
repo_url: https://github.com/mincrmatt12/textle/
docs_dir: docs

nav:
    - Home: "index.md"
    - User Guide:
        - Getting Started: "tut_1.md"
        - The Textlefile: "tut_2.md"

theme:
    name: readthedocs
    custom_dir: docs/_custom

markdown_extensions:
  - admonition
